name: Node.js unit tests

on: [push, pull_request]

jobs:
  test-all:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: poller

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm install
        npm test
    - run: cd ../scaler
    - run: |
        npm install
        npm test
    env:
      CI: true
